### ISSUE TITLE
multi_constellation_settings.m missing

### ISSUE THREAD

**Issue by hadiTab** [goGPS-Project/goGPS_MATLAB#1]
I believe "multi_constellation_settings.m" has been removed from goGPS at some point. The function is still [called](https://github.com/goGPS-Project/goGPS_MATLAB/blob/ad2106db710cbd22e2f01b7e8fc0891612b03c77/goGPS/input_output/RINEX/load_RINEX_nav.m#L49) in "load_RINEX_nav.m" in the case where the constellation struct has been left blank in order to assume GPS.

**Comment by ege010** [comment]
Thanks Hadi!
I just fixed it here: https://github.com/goGPS-Project/goGPS_MATLAB/commit/03bab33a6b5de0a6653e15b4818ee533404e10ef
