### ISSUE TITLE
4digit year in NMEA RMC

### ISSUE THREAD

**Issue by lukegluke** [goGPS-Project/goGPS_MATLAB#10]
in NMEA_RMC_gen.m year is stored like this:

year = sprintf('%02d', date(1,1));
nmeastring = sprintf('$GPRMC,%s%s%s,%c,%s,%c,%s,%c,%s,,%s%s%s,,,,',hour,minute,second,status,phi_nmea,emi_NS,lam_nmea,emi_EW,speed,day,month,year);

so finally in nmea-file there is a date with 4digit year like this: 28022016

but it should be to 2digit-year date: 280216

**Comment by clicat** [comment]
Bug fixed in https://github.com/goGPS-Project/goGPS_MATLAB/commit/cacf4c08da0bd4cc8e22619c97ae46db244f8f85 .
Thanks a lot for the report!
