### ISSUE TITLE
Incorrect information printed

### ISSUE THREAD

**Issue by lukegluke** [goGPS-Project/goGPS_MATLAB#12]
Another one. Incorrect information printed

load_RINEX_nav 157 line when loading nav data for GLONASS fprintf tells that it reads GPS navigation file, instead of GLONASS.

`if(~only_iono), fprintf('%s',['Reading RINEX file ' filename ': ... ']); end`
should be
`if(~only_iono), fprintf('%s',['Reading RINEX file ' [filename(1:end-1) 'g'] ': ... ']); end`

And same thing for other systems, yes.

**Comment by clicat** [comment]
Fixed in rev. https://github.com/goGPS-Project/goGPS_MATLAB/commit/a237ca612cc9d96f1e70bfed17cea92032117305
Thanks @lukegluke!
