### ISSUE TITLE
Use rinex 3.03 mixed flag on navigational file reading

### ISSUE THREAD

**Issue by lukegluke** [goGPS-Project/goGPS_MATLAB#13]
[suggestion]

Rinex 3.03 navigational files contain flag M: MIXED, so it seems to be good to use it in load_RINEX_nav functions when reading such files.

**Comment by lukegluke** [comment]
By the way such nav files one can get from https://igs.bkg.bund.de/dataandproducts/browse#

**Comment by clicat** [comment]
Done some time ago on the new goGPS 1.0 version
