### ISSUE TITLE
sscanf can't parse time information in RINEX v3.xx due to ">"

### ISSUE THREAD

**Issue by lukegluke** [goGPS-Project/goGPS_MATLAB#14]
RINEX_get_epoch, line 139
```
elseif strcmp(lin(1),'>') %RINEX v3.xx
...
% save time information
datee = sscanf(lin(1:min(26,end)),'%f%f%f%f%f%f');
```
It seems that sscanf can't parse time information (return empty) in RINEX v3.xx due to ">" - first symbol.
At least in my Matlab 2016a win64.

Removing ">" from string like this:
`datee = sscanf(lin(2:min(26,end)),'%f%f%f%f%f%f');`
solves my problem.

**Comment by clicat** [comment]
It's been already fixed in rev. https://github.com/goGPS-Project/goGPS_MATLAB/commit/9a1aabea279845069bbcf4c2f1c0e7cded168989#diff-f827e7d91c31c7c579c943858cf79b13

**Comment by lukegluke** [comment]
ok, thanks
