### ISSUE TITLE
Processing rover information bug

### ISSUE THREAD

**Issue by lukegluke** [goGPS-Project/goGPS_MATLAB#15]
With latest goGPS I have this:
![default](https://cloud.githubusercontent.com/assets/3624285/26361609/33085d78-3fe4-11e7-8d64-d5103c82bab8.png)
instead of progress information:
![default](https://cloud.githubusercontent.com/assets/3624285/26362227/fdb1ca5e-3fe5-11e7-9ff7-36dae7377147.png)

Something change between c00d86cabb6a5d334d45e58e35255686575adf74 and 244be8bcfef49442587e33c80fdfa8993ab7bbad

**Comment by clicat** [comment]
Position of the text fixed in rev: https://github.com/goGPS-Project/goGPS_MATLAB/commit/29b438b58d3279bb6a1099612a766cad0a42fc23

**Comment by lukegluke** [comment]
Confirm. Thanks.
![default](https://cloud.githubusercontent.com/assets/3624285/26405015/9cfa8720-409c-11e7-8bbb-d369589ce8fe.png)
