### ISSUE TITLE
Add ability to choose what to output

### ISSUE THREAD

**Issue by lukegluke** [goGPS-Project/goGPS_MATLAB#17]
[Suggestion]
It would be nice to have ability to choose if specific output (NMEA, KML, PDF reports etc.) is needed.

**Comment by clicat** [comment]
solved in branch batch processing (soon to be merged in Main) https://github.com/goGPS-Project/goGPS_MATLAB/commit/af6ce7fd3697c7af0747083bbd8f19df0e3096af
