### ISSUE TITLE
Ask for help: display errors always when running the goGPS.m in v0.5.1 

### ISSUE THREAD

**Issue by wulingnuaa** [goGPS-Project/goGPS_MATLAB#25]
错误使用 connect (line 18)
无法打开到 "igscb.jpl.nasa.gov"、端口 "21" 的连接。

出错 ftp (line 75)
connect(h)

出错 FTP_Downloader (line 104)
                this.ftp_server = ftp(strcat(this.addr, ':',
                this.port));

出错 File_Wizard (line 142)
        function this = File_Wizard(state)

出错 Go_State/initProcessing (line 222)
            fw = File_Wizard;

出错 goGPS (line 155)
gs.initProcessing(); % Set up / download observations and
navigational files

**Comment by wulingnuaa** [comment]
the problem has been solved.

**Comment by ege010** [comment]
Sorry for the late reply, I'll close this for now!
