### ISSUE TITLE
Struct contents reference from a non-struct array object.

### ISSUE THREAD

**Issue by niklgjer** [goGPS-Project/goGPS_MATLAB#30]
While attempting to process code and phase double difference observations, the following error occurred:

Struct contents reference from a non-struct array object.

Error in Go_Wait_Bar/shiftDown (line 450)
            pos = this.h.Position;

Error in goGPS (line 2694)
                                    if (mode_user == 1 && t == 2), w_bar.shiftDown(); end

**Comment by ege010** [comment]
Hi @niklgjer,

thanks, fixed just now! (fa81ea3053a052c744b856d00e29e3bb29b1e9bb)

Eugenio & Andrea
