### ISSUE TITLE
Invalid or deleted object. 

### ISSUE THREAD

**Issue by niklgjer** [goGPS-Project/goGPS_MATLAB#31]
The following error message occurred when trying to process:

Invalid or deleted object.

Error in Go_Wait_Bar/shiftDown (line 450)
            pos = this.h.Position;

Error in goGPS (line 2695)
                                    if (mode_user == 1 && t == 2), w_bar.shiftDown(); end

**Comment by clicat** [comment]
Hi @niklgjer, try to see if the problem still arise... for some reason the handle of the waitbar is created and then appears to be invalid (note that I cannot reproduce the bug, so I'm guessing the solution)

**Comment by niklgjer** [comment]
I updated the program and it seems to be working fine now!
