### ISSUE TITLE
The earth's rotation &relativistic effect&receiver antenna phase offser should be considered 

### ISSUE THREAD

**Issue by gyf900** [goGPS-Project/goGPS_MATLAB#33]
Need ways to access postion of statellite. And also postion of receiver so we can get rid of some obsevation errors. Is there a parameter datasheet for this project?

**Comment by ege010** [comment]
Hi, the quantities included in the issue title are already taken into account:

Earth rotation: https://github.com/goGPS-Project/goGPS_MATLAB/blob/master/goGPS/positioning/satellite_positions.m#L163

Relativistic effect: https://github.com/goGPS-Project/goGPS_MATLAB/blob/master/goGPS/positioning/transmission_time.m#L82

Receiver antenna PCO/PCV: https://github.com/goGPS-Project/goGPS_MATLAB/blob/master/goGPS/goGPS.m#L546

I'll close this issue for now, if there is anything else please add a comment or open a new issue.
Thanks.
Eugenio
