### ISSUE TITLE
Error in downloading the ultra-rapid products

### ISSUE THREAD

**Issue by SteBar** [goGPS-Project/goGPS_MATLAB#34]
goGPS actually is going "faster" than IGS trying to download ultra rapid products that are not already available on the cddis.gsfc.nasa.gov website. 

E.g. At 11/01/2018 15:50 the warning was: 
`**  Initializing download process from cddis.gsfc.nasa.gov:21

 [ WW ] Warning: download of igu19834_12.sp3.Z from cddis.gsfc.nasa.gov:21/pub/gps/products/1983 failed
 [ WW ] Warning: file not found or not accessible` 

On the website was available only igu19834_06.sp3.Z .

**Comment by clicat** [comment]
We will solve the problem in the new release, leaving this issue open as a reminder

**Comment by clicat** [comment]
Now it should be ok
