### ISSUE TITLE
Problems on connecting to the server

### ISSUE THREAD

**Issue by wulingnuaa** [goGPS-Project/goGPS_MATLAB#36]
Dear  Eugenio Realini
      When I run the goGPSnew.m, I always have problems as follows:

   **  Initializing download process from cddis.gsfc.nasa.gov:21

 [ WW ] WARNING: download of igs15654.clk_30s.Z from cddis.gsfc.nasa.gov:21/pub/gps/products/1565 failed
 [ WW ] WARNING: file not found or not accessible

   **  Checking navigational files from G:\matlab\goGPS_MATLAB-masterv0.5.2\goGPS_MATLAB-master\goGPS\..\data\project\default_DD\

 [ WW ] WARNING: G:\matlab\goGPS_MATLAB-masterv0.5.2\goGPS_MATLAB-master\data\satellite\EPH\brdc0060.10n does not exist

   **  Initializing download process from cddis.gsfc.nasa.gov:21

 [ WW ] WARNING: download of brdc0070.10n.Z from cddis.gsfc.nasa.gov:21/pub/gps/products/data/daily/2010/brdc failed
 [ WW ] WARNING: file not found or not accessible

Whether I can run the main program without connected to the server.   
Thank you very much!
Your  sincerely!

**Comment by clicat** [comment]
Dear @wulingnuaa, 
goGPSnew was a temporary script to execute a "newer developmet version" of goGPS, the one that currently we are developing in the "Nightly" branch, it is no longer supported in the Master branch.
We are completely rewriting the software from scratch, ignore that file (we are removing it from Master branch).
