### ISSUE TITLE
inquiring about ITRF Transformation Parameters

### ISSUE THREAD

**Issue by abubakralbashir** [goGPS-Project/goGPS_MATLAB#37]
Hello and lot of thanks for this valuated contribution....
I really had some works in my graduation project about GNSS Data Processing,
and  I applied the ITRF Transformation between ITRF2000 to ITRF2008 using the ITRF parameters provided by the official website of International Terrestrial Reference Frame in the link below, I checked the source of your parameters and I found the transformation parameters are different from that you used in your script.
please check the link : 
[http://itrf.ign.fr/doc_ITRF/Transfo-ITRF2008_ITRFs.txt](url)

**Comment by ege010** [comment]
Hi, sorry for the late reply.
Are you referring to this script? https://github.com/goGPS-Project/goGPS_MATLAB/blob/master/goGPS/utility/geo/itrf2008etrf2000.m
...this applies the transformation from ITRF2008 to ETRF2000, not ITRF2000.
I'm going to close this issue for now, but feel free to re-open it if you wish!
Thanks.
