### ISSUE TITLE
goGPS Version Alpha2 Nightly

### ISSUE THREAD

**Issue by syachroel** [goGPS-Project/goGPS_MATLAB#50]
Dear Dr. Gatti

I have tried Nightly version and running well but first I receive the message : 

[ ok ] Home dir is present
 [ ok ] Observation dir is present
   **   Checking RINEX input files
        - CMAK  (2 ok - 0 ko)
 [ ok ] Observation rinex are present
 [ ok ] Coordinate dir is present
 [ ok ] Meteorological dir is present
 [ ok ] Ocean loading dir is present
 [ WW ] Warning: Atmospheric loading dir is missing (1)
 [ ok ] Antenna dir is present
 [ ok ] Ephemerides dir is present
 [ ok ] Clock Offset dir is present
 [ ok ] Earth Rotation Parameters dir is present
 [ ok ] Satellite Manouvers dir is present
 [ ok ] Differential Code Biases dir is present
 [ ok ] EGNOS Message Center dir is present
 [ ok ] Geoid file is present
 [ ok ] The Geoid is loaded
 [ -- ] Ionospheric corrections disabled
 [ WW ] Warning: Vienna Mapping Function dir is missing (1)

 **[ !! ] Error: Invalid configuration found!!!**

before running well, and a second after finished computation, I check the workstation the data result in its empty also in folder output.
For temporary that's all, thank you for attention

Regards
Syachroel

**Comment by clicat** [comment]
mmm... it's strange that it is saying that the configuration is invalid, I do not see anything wrong (just warnings), but that's normal, the software should create those directories.
For the output, well the new nightly version works in a different way, it produces objects that can be "interrogated" at the end of the processing.

after a successful lunch of goGPS you should run getResults, and in the workspace, you will be able to see the objects rec/rec_list/core
for example by typing rec_list.showZTD you should be able to see the ZTD as computed
(if you executed PPP)

I'm checking the testing function of the configuration in these days, so keep the version updated and in a few days from now re-try to run your project.

Please, attach your config file so I'll be able to understand better what went wrong.

**Comment by syachroel** [comment]
I choose to file ZIMM then the config, I select one by one from PPP setting and setting nightly,...
I think there's default right, and running processing until...getResult, but I check...the workstation still empty, for example, ZTD: NaaN...and HDOP...empty.
...
So I tried with my data, the result it's same...empty

Thanks

**Comment by syachroel** [comment]
great.....thanks Dr.Gatti

I tried today for the last Version goGPS, v 0.6.0 alpha 2 - nightly ...for data ZIMM
The result ....Successfully for temporary, for the next, I will tray for another data

Regard

Syachrul
