### ISSUE TITLE
Night version for Vienna Mapping Function

### ISSUE THREAD

**Issue by syachroel** [goGPS-Project/goGPS_MATLAB#51]
Dear Dr. Gatti,

Night version for Vienna Mapping Function, still not running well

Loading  D:\goGPS_MATLAB-goGPS_nightly\data\reference\VMF\VMFG_20151231.H00
        Loading  D:\goGPS_MATLAB-goGPS_nightly\data\reference\VMF\VMFG_20151231.H06
        Loading  D:\goGPS_MATLAB-goGPS_nightly\data\reference\VMF\VMFG_20151231.H12
        Loading  D:\goGPS_MATLAB-goGPS_nightly\data\reference\VMF\VMFG_20151231.H18
        Loading  D:\goGPS_MATLAB-goGPS_nightly\data\reference\VMF\VMFG_20160101.H00
Error using fgets
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in fgetl (line 33)
[tline,lt] = fgets(fid);

Error in Atmosphere/initVMF (line 303)
            fgetl(fid); %skip one line header

Error in Core/prepareSession (line 239)
                    atmo.initVMF(time_lim_large.first,time_lim_large.last);

Error in Core/go (line 277)
                this.prepareSession(s);

Error in goGPS (line 118)
            core.go(); % execute all
 
>>

**Comment by clicat** [comment]
Hi @syachroel, sorry for my delay in the answer. Does it work now (NightlySmoothSession)?
