### ISSUE TITLE
Cannot rnning GOGPS under  MATLAB

### ISSUE THREAD

**Issue by liyang-whu** [goGPS-Project/goGPS_MATLAB#52]
Excuse me, when I run the latest program under MATLAB, there are a lot of problems. The latest program cannot run like the version 0.4.3.So could you tell me what is wrong and what should l do? Thank you very much.

**Comment by clicat** [comment]
Hi @liyangSKD, I need a bit more information. what do you mean with "the latest? Do you refer to the  Master branch? Or the latest development branch (NightlySmoothSession)? 
What kind of error do you see? What MATLAB version are you using?

**Comment by liyang-whu** [comment]
Hi,I used the latest master branch under MATLAB 2010b.All operations are in accordance with the version 0.4.3.
The errors are as follows.
??? Error using ==> handle
Cannot convert to handle.

Error in ==> Go_State>Go_State.getCurrentSettings at 159
            cur_settings = handle(this.cur_settings);

Error in ==> Core>Core.Core at 61
            this.state = Go_State.getCurrentSettings();

Error in ==> Core>Core.getInstance at 71
                this = Core();

Error in ==> goGPS at 67
core = Core.getInstance();

**Comment by clicat** [comment]
Sorry, @liyangSKD we are currently developing a totally new version in the branch Nightly smooth session, but as far as I know, it should be compatible down to MATLAB 2016a (maybe 2015b). Even the Master version received some updates in the past that drop support to the older MATLAB versions. In my opinion, this is the main reason why you are no more able to run goGPS.
