### ISSUE TITLE
Kalman Filter initialize

### ISSUE THREAD

**Issue by syachroel** [goGPS-Project/goGPS_MATLAB#56]
Dear Dr. Gatti,

Anyway, I still use goGPS master for my processing RINEX data.
Sometimes processing running well, but seldom any warning  

**It was not possible to initialize the Kalman filter.**

Thanks a lot

Regards
Syachrul Arief

**Comment by clicat** [comment]
Aaaaah that’s a totally different story, the new version is a lot better for computing ZTD

**Comment by wakawawiwa** [comment]
Dear All,

I got that problem too, there is appear a warning

**It was not possible to initialize the Kalman filter.**

any suggestion for the problem?

anyway I attach the RINEX files
[RINEX files.zip](https://github.com/goGPS-Project/goGPS_MATLAB/files/2647649/RINEX.files.zip)

Thanks

Regards,
Raka
