### ISSUE TITLE
Some questions about LS_DD_multibaseline.m 

### ISSUE THREAD

**Issue by ryanncheng** [goGPS-Project/goGPS_MATLAB#57]
Dear Dr. Gatti

I take the liberty of disturbing you.

In the routine named LS_DD_multibaseline.m , when computing the Variance-Covariance-Matrix of the float ambiguities , matrix Pg =  G*((G'*(Q^-1)*A)^-1)*A'*(Q^-1);

But, in Instantaneous Estimation of Attitude from GNSS by Hendy Fitrian Suhandri , the VCM of the float ambiguities can be calculated by 
Qaa = [(P^-1)×H'(Q^-1)H - (P^-1)F'×H'(Q^-1)G[F(P^-1)F'×G'(Q^-1)G]^-1*F(P^-1)×G'(Q^-1)H]^-1;

You can see this equation at (3.28) in this paper.

And with this equation, matrix Pg should be calculated as Pg =  G*((G'*(Q^-1)*G)^-1)*G'*(Q^-1);

So I want to know if there any problems in my calculating process or the routine has a minor bug.

for the answer
thank you a lot.

**Comment by clicat** [comment]
Dear @brycheng we have completely rewritten goGPS for static positioning with the least squares approach while the Kalman filter approach for dynamic studies hasn't been re-implemented yet. It could take me a while to have a look back at the old goGPS code. I can say that there could be a bug in the old goGPS version, but to understand whether it is true or not you can directly ask to Dr. Suhandri that is continuously working on this kind of problems, and maybe he can answer you in a faster way. 
@ege010 worked for years on the KF version of goGPS, I'll ask him if he remembers that routine implementation.

**Comment by clicat** [comment]
I talked with Dr. @ege010 and he told me that it's better to contact Dr. Suhandri since he was the original developer of that module. Sorry for the "re-direction" ;-)
