### ISSUE TITLE
run goGPS

### ISSUE THREAD

**Issue by devd1357** [goGPS-Project/goGPS_MATLAB#67]
hi sir,
i am new to this module.
can anyone help me to run this program ..
i tried with GUI but errors are coming.
please help me to find a solution or else send me how to process it if any videos are available...
my mail ID: dev.navic@gmail.com
please do needful...

**Comment by clicat** [comment]
Hello @devd1357, unfortunately, there is not yet any documentation available for this new release of the software (that is a totally new version with respect to < 0.5 versions). This is mainly my fault, we are pushing so much the development that we did not yet arrive in a "feature freeze" state. 
Firstly, we have to finish to move to the new undifferenced uncombined engine, then hopefully we will have time to write a tutorial. 
Do you want to use the software to process in PPP or in differential (NET) mode? 
What version of MATLAB are you using?
Try to start loading default projects, then if you share your errors I can try to help you find a solution, or fix bugs that are still present into the software!
