### ISSUE TITLE
I can't see the Integer Ambiguity Resolution number(quantity,value) = N 

### ISSUE THREAD

**Issue by bkaan05** [goGPS-Project/goGPS_MATLAB#78]
To sum up,
How we can achieve how the program resolves Ambiguity Resolution(N) and GNSS data processing analysis in general ?

**Comment by tagliagiulio** [comment]
The ambiguity resolution is based on the LAMBDA software package. However the package is not included in the repository (due to copyright reason) but can be requested free of charge at https://gnss.curtin.edu.au/research/lambda-and-ps-lambda-software-packages/

**Comment by clicat** [comment]
Since we have no more feedback on the issue, I'm going to close it.
