### ISSUE TITLE
BDS-3  constellations  does not work

### ISSUE THREAD

**Issue by noone77777** [goGPS-Project/goGPS_MATLAB#80]
ERROR:            Selected center: default not compatible with selected            constellations: GC

**Comment by clicat** [comment]
Orbits from IGS do not include Beidou satellite, use CODE MGEX instead

**Comment by noone77777** [comment]
Thanks !
AND  BDS-3  like C35,C36 .e.g   is  also  ok?

**Comment by clicat** [comment]
Honestly, I believe they work, but we never did intensive tests with BeiDou satellites. Since we are located here in Europe, we don't use them on a daily bases.

If you can provide feedback, or if you find any bug, let us know!
