### ISSUE TITLE
Wiki for sub-tabs of Tab-Processing is missing?

### ISSUE THREAD

**Issue by pyuan111** [goGPS-Project/goGPS_MATLAB#84]
Dear goGPS developers,

I am trying to use goGPS for my study on water vapor.
However, it seems that the wiki of the sub-tabs of the Tab Processing is missing.

Clicking the links shows that they are not found:
https://github.com/goGPS-Project/goGPS_MATLAB/ProcessingTab/#tab-data-selection
https://github.com/goGPS-Project/goGPS_MATLAB/ProcessingTab/#tab-atmosphere
https://github.com/goGPS-Project/goGPS_MATLAB/ProcessingTab/#tab-pre-processing
http://github.com/goGPS-Project/goGPS_MATLAB/ProcessingTab/#tab-generic-options
https://github.com/goGPS-Project/goGPS_MATLAB/ProcessingTab/#tab-ppp-parameters
https://github.com/goGPS-Project/goGPS_MATLAB/ProcessingTab/#tab-network-parameters

Could you please add the information to the wiki?

Best regards,
Peng

**Comment by clicat** [comment]
Hi Peng,
     the wiki is a mirror of the documentation present on the website. 
I always suggest to use the website to read documentation, there the links are working:
[https://gogps-project.github.io/wiki/ProcessingTab/#tab-data-selection](https://gogps-project.github.io/wiki/ProcessingTab/#tab-data-selection)

A few newer settings might be missing, we will update the wiki when other planned modifications are finished.
(e.g. added VMF3, more ionex centers....)

**Comment by pyuan111** [comment]
Dear Gatti,
Thanks a lot for your reply.
Best regards,
Peng
