### ISSUE TITLE
Questions on the GNSS data processing for multipath mitigation

### ISSUE THREAD

**Issue by pyuan111** [goGPS-Project/goGPS_MATLAB#86]
Dear goGPS developers,

I am trying to use goGPS to process the GNSS data with multipath effect mitigation.
Assuming that I have one year of daily GNSS observations at a station, for example, ZIMM.
I plan to calculate the multipath map by using congruent grid and Zeenike based interpolation.
I set the window width as 21 days.
I processed the DOY(1–21) data to generate the Maltipath Map (MM(1–21)) and use it to estimate the coordinates and ZTD of DOY(22).
I processed the DOY(2–22) data to generate the MM(2–22) and use it to estimate the coordinates and ZTD of DOY23.
……
I processed the DOY(n–n+20) data to generate the MM(n–n+20) and use it to estimate the coordinates and ZTD of DOY(n+21).

However, I am not sure how to write the codes for a batch processing with a moving window in goGPS command language.
Could you please tell me how can I carry it out?

Best regards,
Peng

**Comment by clicat** [comment]
Dear Peng, can you directly write me an e-mail? we can discuss a bit on this and maybe cooperate. I've have written a paper on Zernike MP maps, but I still need to finish it due to missing time on doing tests, maybe we can help each other.
andrea.gatti at g-red.eu
